import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';

function parseMonorepoYaml(text) {
  const projects = [];
  let current = null;
  let inProjects = false;
  for (const raw of text.split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    if (line === 'projects:') { inProjects = true; continue; }
    if (line.startsWith('- id:')) {
      current = { id: line.split(':')[1].trim(), keywords: [] };
      projects.push(current);
      continue;
    }
    if (!inProjects || !current) continue;
    if (line.startsWith('path:')) current.path = line.split(':')[1].trim();
    if (line.startsWith('type:')) current.type = line.split(':')[1].trim();
    if (line.startsWith('keywords:')) {
      const m = line.match(/\[(.*)\]/);
      if (m) current.keywords = m[1].split(',').map((s) => s.trim().replace(/"/g, ''));
    }
  }
  return { projects, default_in_scope: 'all' };
}

export function loadMonorepoConfig(root) {
  const path = join(root, '.harness/config/monorepo.yaml');
  if (!existsSync(path)) return { projects: [], default_in_scope: 'all' };
  return parseMonorepoYaml(readFileSync(path, 'utf8'));
}

export function detectSubprojects(root) {
  const config = loadMonorepoConfig(root);
  if (config.projects.length) return config.projects;

  const found = [];
  for (const name of readdirSync(root)) {
    const p = join(root, name);
    if (!existsSync(p) || !statSync(p).isDirectory()) continue;
    if (existsSync(join(p, 'package.json'))) {
      found.push({ id: name, path: name, type: 'node', keywords: [name] });
    } else if (existsSync(join(p, 'pom.xml'))) {
      found.push({ id: name, path: name, type: 'maven', keywords: [name] });
    }
  }
  return found;
}

export function inferAffectedProjects(requirement, discovery, projects) {
  const text = `${requirement}\n${discovery || ''}`.toLowerCase();
  const matched = projects.filter((p) =>
    (p.keywords || []).some((kw) => text.includes(String(kw).toLowerCase())),
  );
  if (matched.length) return matched;
  return projects;
}

export function generateMonorepoScope(root, state, options = {}) {
  const projects = detectSubprojects(root);
  const discoveryPath = join(root, state.artifacts?.discovery || '');
  const discovery = existsSync(discoveryPath) ? readFileSync(discoveryPath, 'utf8') : '';
  const inScope = options.inScope || inferAffectedProjects(state.requirement, discovery, projects);
  const inIds = new Set(inScope.map((p) => p.id));
  const outScope = projects.filter((p) => !inIds.has(p.id));

  const sprintNum = options.sprint || 1;
  const yaml = buildScopeYaml(state, sprintNum, inScope, outScope);
  const scopeDir = join(root, '.harness/scope');
  mkdirSync(scopeDir, { recursive: true });
  const outPath = join(scopeDir, `sprint-${sprintNum}.yaml`);
  writeFileSync(outPath, yaml, 'utf8');
  return { path: outPath.replace(`${root}/`, ''), in_scope: inScope.map((p) => p.id), out_scope: outScope.map((p) => p.id) };
}

function buildScopeYaml(state, sprintNum, inScope, outScope) {
  const today = new Date().toISOString().slice(0, 10);
  const inLines = inScope.map((p) => `    - id: "${p.id}"
      path: "${p.path}"
      role: ${p.type === 'maven' ? 'core' : 'integration'}
      note: Autopilot monorepo in-scope`).join('\n');
  const outLines = outScope.map((p) => `    - id: "${p.id}"
      path: "${p.path}"
      reason: 非本需求焦点模块
      decision: freeze`).join('\n');

  return `# Auto-generated by monorepo-scope.mjs
sprint: ${sprintNum}
feature: "${state.feature_id}"
ratified: "${today}"
amended: "${today}"

package_prefix: "."

modules:
  in_scope:
${inLines || '    []'}
  out_of_scope:
${outLines || '    []'}

dependency_rules:
  - from: in_scope
    to: in_scope
    allow: true
  - from: in_scope
    to: out_of_scope
    allow: false
    severity: error

known_violations: []

metadata:
  report_path: .harness/sprints/sprint-${sprintNum}-boundary-report.md
  enforce_in_l2: true
`;
}
