import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

function readJsonSafe(path) {
  try {
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch {
    return null;
  }
}

/**
 * 读取历史 Autopilot 度量，生成策略建议。
 */
export function collectRunMetrics(root) {
  const dir = join(root, '.harness/metrics');
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.startsWith('autopilot-') && f.endsWith('.json'))
    .map((f) => readJsonSafe(join(dir, f)))
    .filter(Boolean);
}

export function analyzeRuns(runs) {
  if (!runs.length) {
    return {
      sample_size: 0,
      recommendations: { tier_default: 'M', max_phase_retries: 2, max_user_stories: 3, max_tasks: 30 },
      stats: {},
    };
  }

  const done = runs.filter((r) => r.status === 'done');
  const failed = runs.filter((r) => r.status === 'failed');
  const rates = runs
    .map((r) => r.execution?.completion_rate)
    .filter((v) => typeof v === 'number');
  const avgCompletion = rates.length
    ? rates.reduce((a, b) => a + b, 0) / rates.length
    : null;

  const tierCounts = { S: 0, M: 0, L: 0 };
  for (const r of runs) {
    if (tierCounts[r.tier] != null) tierCounts[r.tier] += 1;
  }

  const execErrors = failed.filter((r) =>
    (r.errors || []).some((e) => e.phase === 'EXEC' || e.phase === 'EVAL'),
  ).length;

  const recommendations = {
    tier_default: tierCounts.L > tierCounts.M ? 'L' : 'M',
    max_phase_retries: execErrors >= 2 ? 3 : 2,
    max_user_stories: avgCompletion != null && avgCompletion < 0.7 ? 2 : 3,
    max_tasks: avgCompletion != null && avgCompletion < 0.6 ? 20 : 30,
  };

  if (done.length / runs.length >= 0.8 && tierCounts.S >= tierCounts.L) {
    recommendations.tier_default = 'M';
  }

  return {
    sample_size: runs.length,
    stats: {
      success_rate: runs.length ? done.length / runs.length : null,
      avg_completion: avgCompletion,
      tier_counts: tierCounts,
      exec_failures: execErrors,
    },
    recommendations,
    generated_at: new Date().toISOString(),
  };
}

export function writeLearnedPolicy(root, analysis) {
  const out = join(root, '.harness/config/learned-policy.json');
  writeFileSync(out, JSON.stringify(analysis, null, 2), 'utf8');
  return out;
}

/**
 * 将学习策略写回 YAML（autopilot-learned.yaml），供 config 加载器合并。
 */
export function writeLearnedYaml(root, analysis) {
  const r = analysis.recommendations || {};
  const yaml = `# Auto-generated by learn-policy --write · ${analysis.generated_at || new Date().toISOString()}
tier_detection:
  default: ${r.tier_default || 'M'}
gates:
  specify:
    max_user_stories: ${r.max_user_stories ?? 3}
  plan_tasks:
    max_tasks: ${r.max_tasks ?? 30}
autonomy:
  max_phase_retries: ${r.max_phase_retries ?? 2}
`;
  const out = join(root, '.harness/config/autopilot-learned.yaml');
  writeFileSync(out, yaml, 'utf8');
  return out;
}

export function loadLearnedPolicy(root) {
  const path = join(root, '.harness/config/learned-policy.json');
  if (!existsSync(path)) return null;
  return readJsonSafe(path);
}

/**
 * 将学习策略合并到运行时 config（不修改 autopilot.yaml 文件）。
 */
export function applyLearnedPolicy(config, root) {
  const learned = loadLearnedPolicy(root);
  if (!learned?.recommendations) return config;
  const r = learned.recommendations;
  const merged = { ...config, gates: { ...config.gates } };
  merged.tier_detection = { ...config.tier_detection, default: r.tier_default || config.tier_detection?.default };
  merged.gates.specify = { ...config.gates?.specify, max_user_stories: r.max_user_stories ?? 3 };
  merged.gates.plan_tasks = { ...config.gates?.plan_tasks, max_tasks: r.max_tasks ?? 30 };
  merged.autonomy = { ...config.autonomy, max_phase_retries: r.max_phase_retries ?? 2 };
  merged._learned = learned;
  return merged;
}
